sudo: false
language: node_js
node_js:
- '12'
script: npm run build
deploy:
  provider: npm
  script: "cp .npmrc.template $HOME/.npmrc && npm publish"
  skip_cleanup: true
  email: brendan_davies@comcast.com
  api_key: NPM_TOKEN
  on:
    tags: true
    repo: Comcast/hypergard
